default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: rubitter_development
test:
  <<: *default
  database: rubitter_test
production:
  <<: *default
  database: rubitter_production
  username: rubitter
  password: <%= ENV['RUBITTER_DATABASE_PASSWORD'] %>
